server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8167/eureka

logging:
  level:
    root: info
    org:
      springframework.cloud.gateway: TRACE
      springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
        - id: order-service
          uri: lb://order-service
          predicates:
          - Path=/api/v1/order/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/**
        - id: computing-service
          uri: lb://computing-service
          predicates:
            - Path=/api/v1/compute/**
        - id: discovery-server
          uri: http://localhost:8167
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8167
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/so16-realm
