spring:
  application:
    name: order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/order_service_so16_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8167/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    ratelimiters:
      enabled: false
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      customer:
        register-health-indicator: true
        event-consumer-buffer-size: 3
        sliding-window-type: count_based
        sliding-window-size: 10
        failure-rate-threshold: 10
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - pytaichuk.order_service.exception.FindException
          - jakarta.validation.ValidationException
  retry:
    instances:
      customerRetry:
        max-attempts: 2
        wait-duration:
          seconds: 1
        ignore-exceptions:
          - jakarta.validation.ValidationException
          - pytaichuk.order_service.exception.FindException


